In [1]:
import numpy as np

a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [2]:
print(a[0])

1


In [3]:
print(a[-1])

5


In [4]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
print(np.ones((2,2)))

[[1. 1.]
 [1. 1.]]


In [8]:
print(np.arange(0,10,2))

[0 2 4 6 8]


In [10]:
print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


In [11]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [12]:
print(b[0,0])

1


In [13]:
print(b[1,2])

6


In [14]:
a=np.array([10,20,30,40,50])

print(a[1:4])

[20 30 40]


In [15]:
print(a[:3])

[10 20 30]


In [16]:
print(a[::2])

[10 30 50]


In [17]:
a=np.array([1,2,3,4])
b=np.array([10,20,30,40])

print(a+b)

[11 22 33 44]


In [18]:
print(a*b)

[ 10  40  90 160]


In [19]:
print(a**2)

[ 1  4  9 16]


In [20]:
print(np.sum(a))

10


In [21]:
print(np.sum(b))

100


In [22]:
print(np.max(b))

40


In [23]:
print(np.mean(b))

25.0


In [24]:
print(np.sqrt(a))

[1.         1.41421356 1.73205081 2.        ]


In [25]:
print(np.min(b))

10
